apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: web
          image: ghcr.io/kailencodes/orangepi-k3s-lab:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            # Mounting the folder to /data inside the pod
            - name: scanner-data
              mountPath: /usr/share/nginx/html/data
      volumes:
        - name: scanner-data
          hostPath:
            path: /home/orangepi/orangepi-k3s-lab/app
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: default
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
